compiler: gcc

before_install:
  - sudo apt-get install -y spim
  - test -n $CC && unset CC

script:
  - cd codegen && make && make test
  - echo '----'
  - make run_test_cases

notifications:
  email: false