compiler: gcc

before_install:
  - test -n $CC && unset CC

script:
  - cd semantics && make && make test
  - make run && echo '----' && cat main.c
  - echo '----'
  - make run_test_cases

notifications:
  email: false