compiler: gcc

before_install:
  - test -n $CC && unset CC

script:
  - cd semantics && make && make test

after_success:
  - cd semantics && cat main.c && echo '\n' && make run 

notifications:
  email: false