#define YYERROR_VERBOSE

#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include "ast/factory.h"
#include "ast/tostring.h"
#include "typecheck/name_resolution.h"
#include "typecheck/typecheck.h"
#include "./mips_gen/mips_gen.h"

extern int yylex();
extern int yyparse();
extern FILE* yyin;

extern struct decl *abstract_syntax_tree;

/* Clunky: Manually declare the interface to the scanner generated by flex. */
extern char *yytext;


int main(int argc, char* argv[]) {
	if (argc != 3) {
		printf("Must provide 2 arguments\n");
		return 1;
	}
	freopen (argv[2],"w",stdout);
	yyin = fopen(argv[1],"r"); 
	int parse_succesful = yyparse() == 0;
	
	if(parse_succesful) {
		// Create symbol table and perform name resolution
		resolve_symbol_table(abstract_syntax_tree);

		if(pass_type_checks(abstract_syntax_tree)) {
			ast_to_mips(abstract_syntax_tree);
		} else {
			fprintf(stderr, "Typechecking error.\n");
		}
	} else {
		fprintf(stderr, "Parsing error.\n");
	}

	fclose(stdout);
	return 0;
}