#define YYERROR_VERBOSE

#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include "ast/factory.h"
#include "ast/tostring.h"
#include "typecheck/name_resolution.h"
#include "typecheck/typecheck.h"

extern int yylex();
extern int yyparse();
extern FILE* yyin;

extern struct decl *abstract_syntax_tree;

/* Clunky: Manually declare the interface to the scanner generated by flex. */
extern char *yytext;


// TODO: Traverse AST and perform symbol checks

int main(int argc, char* argv[]) {
	if (argc != 3) {
		printf("Must provide 2 arguments\n");
		return 1;
	}
	freopen (argv[2],"w",stdout);
	yyin = fopen(argv[1],"r"); 

	do {
		yyparse();
	} while(!feof(yyin));

	// Initalize symbol table
	init_symbol_table();
	// Populate symbol table
	decl_resolve(abstract_syntax_tree);

	if(pass_type_checks(abstract_syntax_tree)) {
		char *ast = stringify_abstract_syntax_tree(abstract_syntax_tree);	
		printf("%s\n", ast);
		free(ast);
	}

	fclose(stdout);
	return 0;
}